### PR TITLE
Convert

### PR DESCRIPTION
**Pull request by synixebrett**
**When merged this pull request will:**
- Add `hemtt convert`

Requires #47

### CODE REVIEW

**Comment by jonpas** [comment]
Convert Config might be a better name? Convert alone could mean a lot of things, I wouldn't think of converting configuration file as one of the first.

**Comment by synixebrett** [comment]
Yeah, I original had `ConvertProjectFile`, but felt that was a bit long. `ConvertConfig` can work.

**Comment by jonpas** [comment]
`ConvertConfig` could also mean Arma config, but that doesn't make that much sense anyways.

**Comment by synixebrett** [comment]
I'll go with `ConvertProject` I think

**Pull request merged**
